controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Laser = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 5 5 5 . . . . . . . 
        . . . . . 5 5 4 5 5 . . . . . . 
        . . . . . 5 4 4 4 5 . . . . . . 
        . . . . . 5 4 2 4 5 . . . . . . 
        . . . . . . 5 2 5 . . . . . . . 
        . . . . . . . 2 . . . . . . . . 
        . . . . . . . 2 . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Minave, 0, -100)
    music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.InBackground)
})
info.onScore(100, function () {
    scene.setBackgroundImage(img`
        ffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffff5fffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffff
        ffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffff5ffffff
        fffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffff5fffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaacccccccccccccccccaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaacccccccccccccccccccccccaaaaaaaaaaaafffffffffffffffffffffffffff5ffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaacccccccccccccccccccccccccccaaaaaaaaaaaffffffffffff5ffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffff5fffffffffffffffffffffffffffaaaaaaaaaacccccccccccccccccccccccccccccccccaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffff5ffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaacccccccccccccccccccccccccccccccccccaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffff5ffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaacccccccccccccccccccccccccccccccccccccccaaaaaaaaaffffffffffffffffffffffffffffffff5ffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaacccccccccccccccccccccccccccccccccccccccccaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaacccccccccccccccbbbbbbbbbbbbbbbcccccccccccccaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffff5ffffffffffffffaaaaaaaccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffff5fffffffffffffffffffffffffffffffaaaaaaacccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaacccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccaaaaaaafffffffffffff5fffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffff5ffffffffffffffffffffaaaaaaaccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccaaaaaaaffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccaaaaaaafffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccccbbbbbbbbbbbbbdddddddddddddbbbbbbbbbbbbbcccccccaaaaaaafffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccccbbbbbbbbbbbdddddddddddddddddddbbbbbbbbbbbcccccccaaaaaaaffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccccbbbbbbbbbbdddddddddddddddddddddddbbbbbbbbbbcccccccaaaaaaffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccccbbbbbbbbbdddddddddddddddddddddddddbbbbbbbbbcccccccaaaaaaafffffffffffffffffffffff5fffffffffffffffffff
        fffff5ffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccbbbbbbbbbdddddddddddddddddddddddddddbbbbbbbbbccccccaaaaaaaffffffffffffffffffffffffffffffffff5ffffffff
        ffffffffffffffffffffffffffffffffffffffffffffaaaaaaccccccccbbbbbbbbddddddddddbbbbbbbbbbbddddddddddbbbbbbbbccccccaaaaaafffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccbbbbbbbbdddddddbbbbbbbbbbbbbbbbbdddddddbbbbbbbbccccccaaaaaaaffffffffffffffffffffffffffffffffffffffffff
        fffffffffffff5fffffffffffffffffffffffffffffaaaaaaccccccccbbbbbbbbdddddddbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbbccccccaaaaaaffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffaaaaaaccccccccbbbbbbbdddddddbbbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbccccccaaaaaaffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffff5ffffffffffffffffffaaaaaacccccccbbbbbbbdddddddbbbbbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbcccccaaaaaaffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaaccccccccbbbbbbbddddddbbbbbbbbbbbbbbbbbbbbbbbbbddddddbbbbbbbccccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaaccccccccbbbbbbddddddbbbbbbbbbcccccccccbbbbbbbbbddddddbbbbbbccccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbbdddddbbbbbbbbcccccccccccccbbbbbbbbdddddbbbbbbbcccccaaaaaaffffffff5ffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbbdddddbbbbbbbcccccccccccccccbbbbbbbdddddbbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbddddddbbbbbbcccccaaaaaaacccccbbbbbbddddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbbcccaaaaaaaaaaacccbbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbccccaaaaaaaaaaaccccbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffff5fffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaaffffffffffffffffff5ffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaaffffffffffffffffffffffffffffffff5ffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffff5fffffffffffaaaaaacccccccbbbbbbdddddbbbbbbcccaaaaaaaaaaaaacccbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbccccaaaaaaaaaaaccccbbbbbbdddddbbbbbbcccccaaaaaaffffff5ffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbbcccaaaaaaaaaaacccbbbbbbbdddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        fffffffffffffff5ffffffffffffffffffffffffffaaaaaacccccccbbbbbbddddddbbbbbbcccccaaaaaaacccccbbbbbbddddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbbcccccccccccccccbbbbbbbdddddbbbbbbcccccaaaaaaffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddbbbbbbbbcccccccccccccbbbbbbbbdddddbbbbbbcccccaaaaaaffffffffffffffffff5fffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbddddddbbbbbbbbbcccccccccbbbbbbbbbddddddbbbbbbcccccaaaaaaffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccbbbbbbddddddbbbbbbbbbbbbbbbbbbbbbbbbbddddddbbbbbbcccccaaaaaaaffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffaaaaaacccccccbbbbbbdddddddbbbbbbbbbbbbbbbbbbbbbbbdddddddbbbbbbcccccaaaaaafffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccbbbbbbdddddddbbbbbbbbbbbbbbbbbbbbbdddddddbbbbbbcccccaaaaaaafffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccbbbbbbbdddddddbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbcccccaaaaaaaffffffffffffffffffffffffffffffff5ffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffaaaaaaccccccccbbbbbbbdddddddbbbbbbbbbbbbbbbbbdddddddbbbbbbbccccccaaaaaaffffffffffffffffffffffffffffffffffffffffffff
        ffffffff5fffffffffffffffffffffffff5ffffffffffaaaaaaaccccccccbbbbbbddddddddddbbbbbbbbbbbddddddddddbbbbbbccccccaaaaaaaffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffaaaaaaacccccccbbbbbbbbdddddddddddddddddddddddddddbbbbbbbbcccccaaaaaaafffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccbbbbbbbbdddddddddddddddddddddddddbbbbbbbbccccccaaaaaaafffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccbbbbbbbbdddddddddddddddddddddddbbbbbbbbccccccaaaaaaaffffffff5fffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccbbbbbbbbbdddddddddddddddddddbbbbbbbbbccccccaaaaaaafffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaccccccccbbbbbbbbbbbdddddddddddddbbbbbbbbbbbccccccaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccaaaaaaafffffffffffffffffffffff5fffffffffffffffffffffffff
        fffffffffffffffffff5fffffffffffffffffffffffffffffffaaaaaaaaccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbccccccccaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaacccccccccccbbbbbbbbbbbbbbbbbbbbbcccccccccaaaaaaaaaffffff5fffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaacccccccccccccbbbbbbbbbbbbbbbcccccccccccaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaacccccccccccccccccccccccccccccccccccaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaacccccccccccccccccccccccccccccccccaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaacccccccccccccccccccccccccccaaaaaaaaaaafffffffffffffffffffffffffffffffffffffff5fffffffffffffff
        ffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffaaaaaaaaaaaacccccccccccccccccccccccaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaacccccccccccccccccaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffff5fffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffff
        ffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffff5ffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        `)
    info.setLife(3)
    game.showLongText("Felicitaciones!!", DialogLayout.Bottom)
    game.showLongText("Evitaste la lluvia de meteoritos", DialogLayout.Bottom)
    game.showLongText("Ahora debes protegerte de los cometas y ademas meteoritos de nuevo", DialogLayout.Bottom)
    game.showLongText("Para luego cruzar el portal y encontrar la vida en saturno", DialogLayout.Bottom)
    game.showLongText("Tienes que llevar 2 ejemplares, macho y hembra", DialogLayout.Bottom)
    game.showLongText("Para poder tener mas en el futuro", DialogLayout.Bottom)
})
info.onScore(200, function () {
    scene.setBackgroundImage(img`
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfbbbbbbbb
        bbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        `)
    info.setLife(3)
    game.showLongText("Finalmente te enfrentas al jefe", DialogLayout.Bottom)
    game.showLongText("Derrotalo para salvar a tu familia", DialogLayout.Bottom)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(Comida)
    info.changeLifeBy(1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    sprites.destroy(sprite, effects.fire, 100)
    info.changeScoreBy(10)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeLifeBy(-1)
})
let Enemigo_3: Sprite = null
let ENEMIGO_20: Sprite = null
let Enemigo: Sprite = null
let Comida: Sprite = null
let Laser: Sprite = null
let Minave: Sprite = null
music.play(music.createSong(hex`0078000408030200001c00010a006400f4016400000400000000000000000000000000050000043d0004000800012908000c00011e10001400012c1400180001242400280001272c00300001253000340001253400380001254c00500002222c54005800012504001c00100500640000041e000004000000000000000000000000000a0400045f000000040001270400080001240c0010000224271400180001251c00200002272920002400021e2a28002c0002272930003400012a38003c0001273c00400002272a40004400012744004800012a4c005000012754005800012258005c000129`), music.PlaybackMode.LoopingInBackground)
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbdddddbbbbdbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbddddddddddddddddbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbdddddddddddddddddddddbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbdddddddddddddddddddddddddbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddddbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbdddddddddddddddddddddddddddddddddddddddbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddbbffffffffffffffffffffff1fffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddddddddddddbbffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddddddddddddddbbfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbdddddddddddddddddddddddddddddddddddddddddddddddbbbffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddddddddddddddddbbffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff1fffffffffffbddddddddddddddddddddddddddddddddddddddddddddddddddbffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddddddddddddddddddbbfffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffff1ffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddbbbffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddddbbffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddddddddddddddddddddddddbbbaaaaaaaffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffbddddddddddddddddddddddddddddddddddddddddddddddddddddddbb3333333afffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbbaaaaaa33affffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbbcc33aaa3affffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbbcc3333aa3afffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbbccca33aa33affffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbbccca33aa333afffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffaffbddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbfca333a3a333affffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffaaacccccbddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbffa33aa3aa33afffffffffffffffffff1ffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffaa33aaccccbdddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbffa33aaa3a33affffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffa333aaaacccbddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbfa333aa33a33affffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffa333333aaacbdddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbaa3333aa33a33affffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffaa333aaaaaaffbddddddddddddddddddddddddddddddddddddddddddddddddddddbbbba3333aa3a3a333affffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffa3333aaaffffffbdddddddddddddddddddddddddddddddddddddddddddddddddddbbbba333aa333a3a3aafffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffa333aaafafffffbdddddddddddddddddddddddddddddddddddddddddddddddddddbbaa33aa3333afafafffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffaa3333a33aaaffffbbbbbbbbbdddddddddddddddddddddddddddddddddddddddddda333baa333333aaaaffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffaa33b33aa33aaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaa3333bb3333aaaaaffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffa333b333aa333a333333333aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbaaaaaafaaafffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffa333b3333aaa33aaaaa333333aaa333333333333333aaaaaaaaaaaabbbbbbbbbbbbbbb3333333aaffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffa33b33333afaaa3333aa3333333aaaaaaaaaaaaaaa3333333333bb3333333333333333333aaaafffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffa333bb3333aaaaaaaafbaaaaaaaaaaaaaaaaaaaaaaaaaa3333bb333333333333333333aaaaaaffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffaa33bb3333333aaaaabaaa333bbbbbbbbbbbbb3333333aaaaaaaaaaaaaaaaaaaaaaaaabffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffaa33bb3333333333baaaa333333333333333bbb333333aaa3333333aaaaabbaaaabbfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffaa33bbbbbbbbb3bbbaaaaaaaaaabbbbbbbaaaaaaaaa3333333aaabbbbaaabbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffaaa33333333bbb33333abbbbb3333333333333333aaaaaaaaaaaaabbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffff1fffffffffffffffffffffffffffffffffffffaaa333333333333333aaaaaaa3333aaaaaaaaaaaabbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffff1ffffff
    ffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbdddbbbbbbfffffffffffffffffffff1fffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffff1fffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbddddddddddddddddddddddddddddddddddddbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbdddddddddddddddddddddddddddddddddbbbbbbbfffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddddddbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbddddddddddddddddddddddddddbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbdddddddddddddddddbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbdddddddbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
Minave = sprites.create(img`
    . . . . . . 2 2 2 . . . . . . . 
    . . . . 2 2 2 6 2 2 . . . . . . 
    . . . 2 2 6 6 6 6 2 2 2 . . . . 
    5 . . 6 6 6 6 6 6 6 6 6 . . 5 . 
    5 . . 6 6 6 2 2 2 6 6 6 . . 5 . 
    5 . 2 6 6 6 2 9 2 6 6 6 2 . 5 . 
    5 2 2 6 6 6 2 2 2 6 6 6 2 2 5 . 
    5 2 . 6 6 6 6 6 6 6 6 6 . 2 5 . 
    5 . . 6 6 6 6 6 6 6 6 6 . . 5 . 
    . . . . 6 6 6 6 6 6 6 . . . . . 
    . . . . . f f f f f . . . . . . 
    . . . . d d d d d d d . . . . . 
    . . . f f f f f f f f f . . . . 
    . . . . . 2 4 4 4 2 . . . . . . 
    . . . . . . 2 4 2 . . . . . . . 
    . . . . . . . 2 . . . . . . . . 
    `, SpriteKind.Player)
Minave.setStayInScreen(true)
info.setLife(3)
Minave.setPosition(80, 110)
controller.moveSprite(Minave, 200, 200)
info.setScore(0)
game.showLongText("Los cientificos creen que hace mucho tiempo existia vida en saturno, pero debido a una fuerte explocion esa especie dejo de vivir.", DialogLayout.Bottom)
game.showLongText("Tu eres un viajero del tiempo y retrocediste hasta 8000 A.C.", DialogLayout.Bottom)
game.showLongText("Mira, a lo lejos se ve saturno, pero antes debes defenderte de la lluvia de meteoritos", DialogLayout.Bottom)
forever(function () {
    if (info.score() >= 200) {
        sprites.destroy(Enemigo)
        sprites.destroy(ENEMIGO_20)
    }
})
game.onUpdateInterval(500, function () {
    Enemigo = sprites.create(img`
        . . . 2 2 2 2 2 4 2 2 2 2 2 2 . 
        . . . 2 4 4 4 4 4 4 4 4 4 2 2 . 
        . . . 4 4 4 5 5 5 4 5 5 4 2 2 . 
        . . . 4 5 5 5 5 5 5 5 5 5 4 2 2 
        . . 4 5 5 5 5 5 5 5 5 5 5 4 2 2 
        . 4 4 5 e e e e e e e 5 5 5 4 2 
        . 4 5 e e e e e e e e e 5 5 4 2 
        . 4 e e e e b e e e e e e 5 4 . 
        . . e e b b b e e e e e e 5 4 . 
        . . e e b b e e e e b b e 4 4 . 
        . . e e e e e e e e e b e . . . 
        . . e e e e e e e e e b e . . . 
        . . e e e e e e e e e e e . . . 
        . . e e e e b b b e e e e . . . 
        . . . e e e e e b e e e . . . . 
        . . . . e e e e e e e . . . . . 
        `, SpriteKind.Enemy)
    Enemigo.setVelocity(0, 100)
    Enemigo.setPosition(randint(0, 120), 0)
})
game.onUpdateInterval(500, function () {
    if (info.score() >= 100) {
        ENEMIGO_20 = sprites.create(img`
            .........eeeeee...................................
            ....eeeeeeeeeee...................................
            ...eeeeeee222ee...................................
            .eeeeee222222ee...................................
            .eeeee222222eee...................................
            eeee22222222ee....................................
            ee222222222eee....................................
            e2222222222eee....................................
            22233332222eee....................................
            2233333222eee.....................................
            333333322eeee.....................................
            331113322eee......................................
            311113222ee.......................................
            31111322ee........................................
            331133eee.........................................
            33333ee...........................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            `, SpriteKind.Enemy)
        ENEMIGO_20.setVelocity(0, 120)
        ENEMIGO_20.setPosition(randint(0, 160), 3)
    }
})
game.onUpdateInterval(500, function () {
    if (info.score() >= 200) {
        Enemigo_3 = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . f f f f f f f f . . . . 
            . . . f f 9 9 9 9 9 9 f f . . . 
            . . f f 9 9 9 9 9 9 9 9 f f f . 
            . . f 9 9 9 9 9 9 9 9 f f 9 f f 
            . . f f f f f f f f f f 9 9 9 f 
            . . f f 9 9 1 1 9 f f 9 9 9 9 f 
            . . f 9 9 1 1 9 9 f 9 9 9 9 9 f 
            . . f 9 1 1 9 9 9 f 9 9 9 9 9 f 
            . . f 1 1 9 9 9 9 f 9 9 9 9 9 f 
            . . f 9 9 9 1 1 1 f 9 9 9 9 9 f 
            . . f 9 9 9 1 9 9 f 9 9 9 f f f 
            . . f 9 9 1 9 9 9 f 9 f f f . . 
            . . f f f f f f f f f f . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Enemy)
        Enemigo_3.setVelocity(0, randint(100, 170))
        Enemigo_3.setPosition(randint(0, 120), 0)
    }
})
game.onUpdateInterval(10000, function () {
    Comida = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . e e 4 4 4 4 . . . . . . . . 
        . e 4 4 4 4 4 4 4 . . . . . . . 
        . . e e e e e e . . . . . . . . 
        6 6 7 6 7 7 6 6 7 . . . . . . . 
        . . 2 2 2 2 2 3 . . . . . . . . 
        . e e 4 4 4 4 4 e . . . . . . . 
        . . e e 4 4 4 e . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    Comida.setPosition(randint(110, 0), randint(0, 160))
})
